// Tesla ETF holdings data converted from CSV to compact [ticker, fullName, percentage] format
const tslaETFData = [
  ["TSLL", "Direxion Daily TSLA Bull 2X Shares", "100.00"],
  ["TESL", "Simplify Volt TSLA Revolution ETF", "25.57"],
  ["BTAL", "AGF U.S. Market Neutral Anti-Beta Fund", "24.73"],
  ["NITE", "The Nightview ETF", "20.06"],
  ["XLY", "The Consumer Discretionary Select Sector SPDR Fund", "15.17"],
  ["FDIS", "Fidelity MSCI Consumer Discretionary Index ETF", "13.70"],
  ["VCR", "Vanguard Consumer Discretionary Index Fund ETF Shares", "13.06"],
  ["ARKK", "ARK Innovation ETF", "11.49"],
  ["UCC", "ProShares Ultra Consumer Services", "11.42"],
  ["RXI", "iShares Global Consumer Discretionary ETF", "10.88"],
  ["SFYF", "SoFi Social 50 ETF", "9.97"],
  ["SMOG", "VanEck Low Carbon Energy ETF", "8.85"],
  ["WANT", "Direxion Daily Cnsmr Discret Bull 3XShrs", "8.52"],
  ["ARKW", "ARK Next Generation Internet ETF", "8.24"],
  ["IYC", "iShares US Consumer Discretionary ETF", "8.03"],
  ["QQQU", "Direxion Shares ETF Trust - Direxion Daily Magnificent 7 Bull 2X Shares", "7.91"],
  ["FTXR", "First Trust Nasdaq Transportation ETF", "7.90"],
  ["QCLN", "First Trust NASDAQ Clean Edge Green Energy Index Fund", "7.73"],
  ["FIVY", "YieldMax Dorsey Wright Hybrid 5 Income ETF", "7.37"],
  ["SPRX", "Spear Alpha ETF", "6.95"],
  ["LSGR", "Natixis Loomis Sayles Focused Growth ETF", "6.21"],
  ["FDG", "American Century Focused Dynamic Growth ETF", "5.96"],
  ["AMOM", "QRAFT AI-Enhanced U.S. Large Cap Momentum ETF", "5.83"],
  ["LIT", "Global X Lithium & Battery Tech ETF", "5.46"],
  ["ULTY", "YieldMax Ultra Option Income Strategy ETF", "5.32"],
  ["ACES", "ALPS Clean Energy ETF", "5.30"],
  ["YALL", "God Bless America ETF", "5.05"],
  ["EGGS", "NestYield Total Return Guard ETF", "5.04"],
  ["EGGY", "NestYield Dynamic Income ETF", "4.99"],
  ["CEPI", "REX Crypto Equity Premium Income ETF", "4.97"],
  ["EGGQ", "NestYield Visionary ETF", "4.90"],
  ["EV", "Mast Global Battery Recycling & Production ETF", "4.71"],
  ["CGGR", "Capital Group Growth ETF", "4.69"],
  ["GPTY", "YieldMax AI & Tech Portfolio Option Income ETF", "4.29"],
  ["TXS", "Texas Capital Texas Equity Index ETF", "4.28"],
  ["EVAV", "Direxion Daily Electric and Autonomous Vehicles Bull 2X Shares", "4.20"],
  ["ERTH", "Invesco MSCI Sustainable Future ETF", "4.18"],
  ["QDVO", "Amplify CWP Growth & Income ETF", "4.12"],
  ["LQAI", "LG QRAFT AI-Powered U.S. Large Cap Core ETF", "4.00"],
  ["MOTO", "SmartETFs Smart Transportation & Technology ETF", "3.98"],
  ["BATT", "Amplify Lithium & Battery Technology ETF", "3.98"],
  ["MTUM", "iShares MSCI USA Momentum Factor ETF", "3.95"],
  ["PALC", "Pacer Lunt Large Cap Multi-Factor Alternator ETF", "3.93"],
  ["PP", "The Meet Kevin Pricing Power ETF", "3.93"],
  ["CCSO", "Carbon Collective Climate Solutions U.S. Equity ETF", "3.68"],
  ["STLG", "iShares MSCI USA Quality GARP ETF", "3.65"],
  ["MVPS", "Amplify Thematic All-Stars ETF", "3.61"],
  ["NACP", "Impact Shares NAACP Minority Empowerment ETF", "3.55"],
  ["AIFD", "TCW Artificial Intelligence ETF", "3.54"],
  ["IWY", "iShares Russell Top 200 Growth ETF", "3.51"],
  ["QQQA", "ProShares Nasdaq-100 Dorsey Wright Momentum ETF", "3.46"],
  ["HLAL", "Wahed FTSE USA Shariah ETF", "3.46"],
  ["NZUS", "SPDR MSCI USA Climate Paris Aligned ETF", "3.31"],
  ["GIAX", "Nicholas Global Equity and Income ETF", "3.31"],
  ["CARZ", "First Trust S-Network Future Vehicles & Technology ETF", "3.24"],
  ["MGK", "Vanguard Mega Cap Growth Index Fund", "3.23"],
  ["ETEC", "iShares Breakthrough Environmental Solutions ETF", "3.19"],
  ["BUZZ", "VanEck Social Sentiment ETF", "3.18"],
  ["GQQQ", "Astoria US Quality Growth Kings ETF", "3.18"],
  ["IVW", "iShares S&P 500 Growth ETF", "3.18"],
  ["SPYG", "SPDR Portfolio S&P 500 Growth ETF", "3.16"],
  ["CNEQ", "Alger Concentrated Equity ETF", "3.15"],
  ["USSG", "Xtrackers MSCI USA Selection Equity ETF", "3.11"],
  ["ONEQ", "Fidelity Nasdaq Composite Index ETF", "3.11"],
  ["IQSU", "NYLI Candriam U.S. Large Cap Equity ETF", "3.10"],
  ["SCHG", "Schwab U.S. Large-Cap Growth ETF", "3.09"],
  ["DSI", "iShares ESG MSCI KLD 400 ETF", "3.09"],
  ["HQGO", "Hartford US Quality Growth ETF", "3.08"],
  ["EGUS", "Ishares ESG Aware MSCI USA Growth ETF", "3.08"],
  ["QFLR", "Innovator Nasdaq-100 Managed Floor ETF", "3.08"],
  ["FTQI", "First Trust Nasdaq BuyWrite Income ETF", "3.07"],
  ["KARS", "KraneShares Electric Vehicles and Future Mobility Index ETF", "3.07"],
  ["PABU", "iShares Paris-Aligned Climate MSCI USA ETF", "3.06"],
  ["VOOG", "Vanguard S&P 500 Growth Index Fund ETF Shares", "3.05"],
  ["SUSL", "iShares ESG MSCI USA Leaders ETF", "3.04"],
  ["ILCG", "iShares Morningstar Growth ETF", "2.99"],
  ["IUSG", "iShares Core S&P U.S. Growth ETF", "2.98"],
  ["QQH", "HCM Defender 100 Index ETF", "2.96"],
  ["PGRO", "Putnam Focused Large Cap Growth ETF", "2.95"],
  ["USMC", "Principal U.S. Mega-Cap ETF", "2.90"],
  ["BRIF", "FIS Bright Portfolios Focused Equity ETF", "2.89"],
  ["IWF", "iShares Russell 1000 Growth ETF", "2.88"],
  ["RND", "First Trust Bloomberg R&D Leaders ETF", "2.84"],
  ["IDRV", "iShares Self-Driving EV and Tech ETF", "2.83"],
  ["TUGN", "STF Tactical Growth & Income ETF", "2.83"],
  ["QGRW", "Wisdomtree U.S. Quality Growth Fund", "2.81"],
  ["XLG", "Invesco S&P 500 Top 50 ETF", "2.78"],
  ["QCLR", "Global X NASDAQ 100 Collar 95-110 ETF", "2.77"],
  ["MMTM", "SPDR S&P 1500 Momentum Tilt ETF", "2.77"],
  ["VUG", "Vanguard Growth Index Fund ETF Shares", "2.76"],
  ["FELG", "Fidelity Enhanced Large Cap Growth ETF", "2.75"],
  ["QQQI", "NEOS NASDAQ-100(R) High Income ETF", "2.75"],
  ["QTR", "Global X NASDAQ 100 Tail Risk ETF", "2.73"],
  ["QYLG", "Global X Nasdaq 100 Covered Call & Growth ETF", "2.73"],
  ["QHDG", "Innovator Hedged Nasdaq-100 ETF", "2.73"],
  ["QQQ", "Invesco QQQ Trust", "2.73"],
  ["QQQH", "NEOS Nasdaq-100 Hedged Equity Income ETF", "2.72"],
  ["VONG", "Vanguard Russell 1000 Growth Index Fund ETF Shares", "2.71"],
  ["DARP", "Grizzle Growth ETF", "2.71"],
  ["QYLD", "Global X NASDAQ 100 Covered Call ETF", "2.71"],
  ["QRMI", "Global X NASDAQ 100 Risk Managed Income ETF", "2.71"],
  ["BBLU", "Ea Bridgeway Blue Chip ETF", "2.70"],
  ["HBTA", "Horizon Expedition Plus ETF", "2.69"],
  ["TUG", "STF Tactical Growth ETF", "2.64"],
  ["CATH", "Global X S&P 500 Catholic Values ETF", "2.62"],
  ["XOVR", "ERShares Private-Public Crossover ETF", "2.61"],
  ["AGIX", "KraneShares Artificial Intelligence and Technology ETF", "2.61"],
  ["SPUS", "SP Funds S&P 500 Sharia Industry Exclusions ETF", "2.59"],
  ["IQQQ", "ProShares Nasdaq-100 High Income ETF", "2.56"],
  ["JGRO", "JPMorgan Active Growth ETF", "2.52"],
  ["PJFG", "PGIM Jennison Focused Growth ETF", "2.50"],
  ["ALAI", "Alger AI Enablers & Adopters ETF", "2.43"],
  ["QSIX", "Pacer Metarus Nasdaq 100 Dividend Multiplier 600 ETF", "2.38"],
  ["AOTG", "AOT Growth and Innovation ETF", "2.38"],
  ["QLD", "ProShares Ultra QQQ", "2.34"],
  ["CLNR", "NYLI Cleaner Transport ETF", "2.33"],
  ["SNPE", "Xtrackers S&P 500 Scored & Screened ETF", "2.31"],
  ["USCL", "Ishares Climate Conscious & Transition MSCI USA ETF", "2.31"],
  ["GRNY", "Tidal Trust III - Fundstrat Granny Shots US Large Cap ETF", "2.31"],
  ["EFIV", "SPDR S&P 500 ESG ETF", "2.30"],
  ["USCA", "Xtrackers MSCI USA Climate Action Equity ETF", "2.29"],
  ["SPXT", "ProShares S&P 500 ex-Technology ETF", "2.27"],
  ["CTEX", "ProShares S&P Kensho Cleantech ETF", "2.27"],
  ["OEF", "iShares S&P 100 ETF", "2.27"],
  ["WINN", "Harbor Long-Term Growers ETF", "2.22"],
  ["QQMG", "Invesco ESG NASDAQ 100 ETF", "2.19"],
  ["FEUS", "FlexShares ESG & Climate US Large Cap Core Index Fund", "2.18"],
  ["AIQ", "Global X Artificial Intelligence & Technology ETF", "2.17"],
  ["PEZ", "Invesco Dorsey Wright Consumer Cyclicals Momentum ETF", "2.17"],
  ["DRIV", "Global X Autonomous & Electric Vehicles ETF", "2.15"],
  ["JEPQ", "JPMorgan Nasdaq Equity Premium Income ETF", "2.13"],
  ["RSPD", "Invesco S&P 500 Equal Weight Consumer Discretionary ETF", "2.12"],
  ["QRFT", "QRAFT AI-Enhanced U.S. Large Cap ETF", "2.12"],
  ["STXG", "Strive 1000 Growth ETF", "2.12"],
  ["BDGS", "Bridges Capital Tactical ETF", "2.09"],
  ["QQA", "Invesco QQQ Income Advantage ETF", "2.08"],
  ["ACGR", "American Century ETF Trust - American Century Large Cap Growth ETF", "2.01"],
  ["QBIG", "Invesco Top QQQ ETF", "2.00"],
  ["FLCG", "Federated Hermes MDT Large Cap Growth ETF", "1.98"],
  ["KQQQ", "Kurv Technology Titans Select ETF", "1.96"],
  ["QQXT", "First Trust NASDAQ-100 Ex-Technology Sector Index Fund", "1.95"],
  ["SPXN", "ProShares S&P 500 ex-Financials ETF", "1.92"],
  ["XNTK", "SPDR NYSE Technology ETF", "1.90"],
  ["GRID", "First Trust NASDAQ Clean Edge Smart Grid Infrastructure Index Fund", "1.89"],
  ["IWL", "iShares Russell Top 200 ETF", "1.89"],
  ["LRGE", "ClearBridge Large Cap Growth ESG ETF", "1.88"],
  ["UPGR", "Xtrackers US Green Infrastructure Select Equity ETF", "1.86"],
  ["FDMO", "Fidelity Momentum Factor ETF", "1.83"],
  ["MGC", "Vanguard Mega Cap Index Fund", "1.80"],
  ["JCTR", "JPMorgan Carbon Transition U.S. Equity ETF", "1.79"],
  ["SPXV", "ProShares S&P 500 ex-Health Care ETF", "1.78"],
  ["MPAY", "Akros Monthly Payout ETF", "1.75"],
  ["XVV", "iShares ESG Select Screened S&P 500 ETF", "1.75"],
  ["IWLG", "NYLI Winslow Large Cap Growth ETF", "1.73"],
  ["NTSX", "WisdomTree U.S. Efficient Core Fund", "1.71"],
  ["FVAL", "Fidelity Value Factor ETF", "1.71"],
  ["TQQQ", "ProShares UltraPro QQQ", "1.71"],
  ["HDUS", "Hartford Disciplined US Equity ETF", "1.66"],
  ["NBDS", "Neuberger Berman Disrupters ETF", "1.65"],
  ["SPXE", "ProShares S&P 500 ex-Energy ETF", "1.65"],
  ["ESGV", "Vanguard ESG U.S. Stock ETF", "1.65"],
  ["PBP", "Invesco S&P 500 BuyWrite ETF", "1.64"],
  ["UDIV", "Franklin U.S. Core Dividend Tilt Index ETF", "1.64"],
  ["PHEQ", "Parametric Hedged Equity ETF", "1.63"],
  ["SPYX", "SPDR S&P 500 Fossil Fuel Reserves Free ETF", "1.63"],
  ["SFLR", "Innovator Equity Managed Floor ETF", "1.63"],
  ["STRV", "Strive 500 ETF", "1.62"],
  ["CVLC", "Calvert US Large-Cap Core Responsible Index ETF", "1.62"],
  ["CNRG", "SPDR Kensho Clean Power ETF", "1.61"],
  ["SPY", "SPDR S&P 500 ETF Trust", "1.60"],
  ["SPLG", "SPDR Portfolio S&P 500 ETF", "1.60"],
  ["IVV", "iShares Core S&P 500 ETF", "1.60"],
  ["BKLC", "BNY Mellon US Large Cap Core Equity ETF", "1.60"],
  ["VOTE", "TCW Transform 500 ETF", "1.60"],
  ["XYLG", "Global X S&P 500 Covered Call & Growth ETF", "1.59"],
  ["XTR", "Global X S&P 500 Tail Risk ETF", "1.59"],
  ["PBUS", "Invesco MSCI USA ETF", "1.59"],
  ["XRMI", "Global X S&P 500 Risk Managed Income ETF", "1.59"],
  ["PEPS", "Parametric Equity Plus ETF", "1.58"],
  ["SUSA", "iShares MSCI USA ESG Select ETF", "1.58"],
  ["IVVW", "iShares S&P 500 BuyWrite ETF", "1.58"],
  ["THNQ", "Robo Global Artificial Intelligence ETF", "1.58"],
  ["XYLD", "Global X S&P 500 Covered Call ETF", "1.58"],
  ["ESGU", "iShares ESG Aware MSCI USA ETF", "1.57"],
  ["TOV", "JLens 500 Jewish Advocacy U.S. ETF", "1.57"],
  ["LBAY", "Leatherback Long/Short Alternative Yield ETF", "1.57"],
  ["UPGD", "Invesco Bloomberg Analyst Rating Improvers ETF", "1.57"],
  ["LCTU", "BlackRock U.S. Carbon Transition Readiness ETF", "1.56"],
  ["XCLR", "Global X S&P 500 Collar 95-110 ETF", "1.56"],
  ["USPX", "Franklin U.S. Equity Index ETF", "1.55"],
  ["VOO", "Vanguard S&P 500 ETF", "1.54"],
  ["PTNQ", "Pacer Trendpilot 100 ETF", "1.53"],
  ["NZAC", "SPDR MSCI ACWI Climate Paris Aligned ETF", "1.53"],
  ["ILCB", "iShares Morningstar U.S. Equity ETF", "1.53"],
  ["JTEK", "JPMorgan U.S. Tech Leaders ETF", "1.52"],
  ["VV", "Vanguard Large Cap Index Fund", "1.51"],
  ["SCHX", "Schwab U.S. Large-Cap ETF", "1.50"],
  ["DFUS", "Dimensional U.S. Equity Market ETF", "1.50"],
  ["KLMN", "Invesco MSCI North America Climate ETF", "1.50"],
  ["SPHB", "Invesco S&P 500 High Beta ETF", "1.49"],
  ["HELO", "Jpmorgan Hedged Equity Laddered Overlay ETF", "1.48"],
  ["USRD", "Themes US R&D Champions ETF", "1.48"],
  ["SPTM", "SPDR Portfolio S&P 1500 Composite Stock Market ETF", "1.47"],
  ["IYY", "iShares Dow Jones U.S. ETF", "1.46"],
  ["SCHK", "Schwab 1000 ETF", "1.46"],
  ["IWB", "iShares Russell 1000 ETF", "1.46"],
  ["MODL", "Victoryshares Westend U.S. Sector ETF", "1.46"],
  ["GQI", "Natixis Gateway Quality Income ETF", "1.45"],
  ["NUGO", "Nuveen Growth Opportunities ETF", "1.44"],
  ["INRO", "iShares U.S. Industry Rotation Active ETF", "1.43"],
  ["QQQM", "Invesco NASDAQ 100 ETF", "1.41"],
  ["VONE", "Vanguard Russell 1000 Index Fund ETF Shares", "1.41"],
  ["SCHB", "Schwab U.S. Broad Market ETF", "1.40"],
  ["QDPL", "Pacer Metaurus US Large Cap Dividend Multiplier 400 ETF", "1.39"],
  ["IWV", "iShares Russell 3000 ETF", "1.39"],
  ["FTGS", "First Trust Growth Strength ETF", "1.39"],
  ["ITOT", "iShares Core S&P Total U.S. Stock Market ETF", "1.39"],
  ["SPUU", "Direxion Daily S&P 500 Bull 2X Shares", "1.38"],
  ["BLKC", "Invesco Alerian Galaxy Blockchain Users and Decentralized Commerce ETF", "1.37"],
  ["ONOF", "Global X Adaptive U.S. Risk Management ETF", "1.36"],
  ["KVLE", "KraneShares Value Line Dynamic Dividend Equity Index ETF", "1.36"],
  ["LGH", "HCM Defender 500 Index ETF", "1.36"],
  ["VTHR", "Vanguard Russell 3000 Index Fund ETF Shares", "1.35"],
  ["APUE", "ActivePassive U.S. Equity ETF", "1.33"],
  ["VTI", "Vanguard Total Stock Market Index Fund ETF Shares", "1.32"],
  ["HCMT", "Direxion HCM Tactical Enhanced U.S. Equity Strategy ETF", "1.29"],
  ["DFAU", "Dimensional US Core Equity Market ETF", "1.27"],
  ["FFND", "The Future Fund Active ETF", "1.26"],
  ["SSO", "ProShares Ultra S&P500", "1.25"],
  ["LEXI", "Alexis Practical Tactical ETF", "1.23"],
  ["LCDS", "JPMorgan Fundamental Data Science Large Core ETF", "1.22"],
  ["KOKU", "Xtrackers MSCI Kokusai Equity ETF", "1.21"],
  ["TOK", "iShares MSCI Kokusai ETF", "1.21"],
  ["HAIL", "SPDR S&P Kensho Smart Mobility ETF", "1.18"],
  ["ZZZ", "CYBER HORNET S&P 500 and Bitcoin 75/25 Strategy ETF", "1.18"],
  ["PBW", "Invesco WilderHill Clean Energy ETF", "1.18"],
  ["DYNF", "iShares U.S. Equity Factor Rotation Active ETF", "1.17"],
  ["ACVF", "American Conservative Values ETF", "1.17"],
  ["TGRT", "T. Rowe Price Growth ETF", "1.17"],
  ["URTH", "iShares MSCI World ETF", "1.14"],
  ["ORR", "Militia Long/Short Equity ETF", "1.14"],
  ["BALI", "iShares Advantage Large Cap Income ETF", "1.13"],
  ["FWD", "AB Disruptors ETF", "1.11"],
  ["DTEC", "ALPS Disruptive Technologies ETF", "1.11"],
  ["QQEW", "First Trust NASDAQ-100 Equal Weighted Index Fund", "1.11"],
  ["QQQE", "Direxion NASDAQ-100 Equal Weighted Index Shares", "1.10"],
  ["EQWL", "Invesco S&P 100 Equal Weight ETF", "1.10"],
  ["KLMT", "Invesco MSCI Global Climate 500 ETF", "1.09"],
  ["MSLC", "Morgan Stanley Pathway Large Cap Equity ETF", "1.08"],
  ["CRBN", "iShares MSCI ACWI Low Carbon Target ETF", "1.08"],
  ["PEXL", "Pacer US Export Leaders ETF", "1.08"],
  ["HIBL", "Direxion Daily S&P 500 High Beta Bull 3X Shares", "1.07"],
  ["MMLG", "First Trust Multi-Manager Large Growth ETF", "1.07"],
  ["FELC", "Fidelity Enhanced Large Cap Core ETF", "1.04"],
  ["SPXL", "Direxion Daily S&P500 Bull 3X Shares", "1.03"],
  ["ACWI", "iShares MSCI ACWI ETF", "1.02"],
  ["ACLC", "American Century ETF Trust - American Century Large Cap Equity ETF", "1.02"],
  ["GURU", "Global X Guru Index ETF", "1.00"],
  ["SATO", "Invesco Alerian Galaxy Crypto Economy ETF", "1.00"],
  ["FTHI", "First Trust BuyWrite Income ETF", "1.00"],
  ["CSM", "ProShares Large Cap Core Plus", "0.99"],
  ["UPRO", "ProShares UltraPro S&P500", "0.98"],
  ["PHDG", "Invesco S&P 500 Downside Hedged ETF", "0.98"],
  ["LRGF", "iShares U.S. Equity Factor ETF", "0.97"],
  ["HIDV", "AB US High Dividend ETF", "0.97"],
  ["DGT", "SPDR Global Dow ETF", "0.95"],
  ["GSPY", "Gotham Enhanced 500 ETF", "0.95"],
  ["SPGM", "SPDR Portfolio MSCI Global Stock Market ETF", "0.93"],
  ["KRMA", "Global X Conscious Companies ETF", "0.90"],
  ["TTEQ", "T. Rowe Price Technology ETF", "0.87"],
  ["LEGR", "First Trust Indxx Innovative Transaction & Process ETF", "0.87"],
  ["FSST", "Fidelity Sustainable U.S. Equity ETF", "0.87"],
  ["ROE", "Astoria US Equal Weight Quality Kings ETF", "0.86"],
  ["VT", "Vanguard Total World Stock Index Fund ETF Shares", "0.86"],
  ["AVSU", "Avantis Responsible U.S. Equity ETF", "0.86"],
  ["DFSU", "Dimensional US Sustainability Core 1 ETF", "0.85"],
  ["FBOT", "Fidelity Disruptive Automation ETF", "0.83"],
  ["ITDI", "Ishares Lifepath Target Date 2065 ETF", "0.83"],
  ["ITDH", "Ishares Lifepath Target Date 2060 ETF", "0.82"],
  ["ITDG", "Ishares Lifepath Target Date 2055 ETF", "0.82"],
  ["RPG", "Invesco S&P 500 Pure Growth ETF", "0.81"],
  ["ITDF", "Ishares Lifepath Target Date 2050 ETF", "0.78"],
  ["EAOA", "iShares ESG Aware 80/20 Aggressive Allocation ETF", "0.78"],
  ["TRFM", "AAM Transformers ETF", "0.78"],
  ["ROPE", "Coastal Compass 100 ETF", "0.77"],
  ["AIEQ", "Amplify AI Powered Equity ETF", "0.76"],
  ["SFY", "SoFi Select 500 ETF", "0.73"],
  ["KOCG", "FIS Knights of Columbus Global Belief ETF", "0.72"],
  ["AOA", "iShares Core 80/20 Aggressive Allocation ETF", "0.71"],
  ["AVLC", "American Century ETF Trust Avan", "0.71"],
  ["ITDE", "Ishares Lifepath Target Date 2045 ETF", "0.70"],
  ["AVUS", "Avantis US Equity ETF", "0.70"],
  ["FEAC", "Fidelity Enhanced U.S. All-Cap Equity ETF", "0.69"],
  ["FTLS", "First Trust Long/Short Equity ETF", "0.69"],
  ["QARP", "Xtrackers Russell 1000 US QARP ETF", "0.69"],
  ["JHML", "John Hancock Multifactor Large Cap ETF", "0.65"],
  ["FXD", "First Trust Consumer Discretionary AlphaDEX Fund", "0.63"],
  ["ITDD", "Ishares Lifepath Target Date 2040 ETF", "0.62"],
  ["JOET", "Virtus Terranova U.S. Quality Momentum ETF", "0.60"],
  ["BTHM", "iShares U.S. Thematic Rotation Active ETF", "0.60"],
  ["EPS", "WisdomTree U.S. LargeCap Fund", "0.59"],
  ["RWL", "Invesco S&P 500 Revenue ETF", "0.59"],
  ["EAOR", "iShares ESG Aware 60/40 Balanced Allocation ETF", "0.58"],
  ["IUS", "Invesco RAFI Strategic US ETF", "0.57"],
  ["ETHO", "Amplify Etho Climate Leadership U.S. ETF", "0.57"],
  ["SZNE", "Pacer CFRA-Stovall Equal Weight Seasonal Rotation ETF", "0.56"],
  ["DCOR", "Dimensional US Core Equity 1 ETF", "0.55"],
  ["LRND", "NYLI U.S. Large Cap R&D Leaders ETF", "0.55"],
  ["ITDC", "Ishares Lifepath Target Date 2035 ETF", "0.55"],
  ["VLU", "SPDR S&P 1500 Value Tilt ETF", "0.55"],
  ["PSTR", "PeakShares Sector Rotation ETF", "0.53"],
  ["AOR", "iShares Core 60/40 Balanced Allocation ETF", "0.53"],
  ["FTC", "First Trust Large Cap Growth AlphaDEX Fund", "0.50"],
  ["GLOF", "iShares Global Equity Factor ETF", "0.47"],
  ["HLGE", "Hartford Longevity Economy ETF", "0.45"],
  ["FLCC", "Federated Hermes MDT Large Cap Core ETF", "0.45"],
  ["ITDB", "Ishares Lifepath Target Date 2030 ETF", "0.45"],
  ["ROBT", "First Trust Nasdaq Artificial Intelligence and Robotics ETF", "0.44"],
  ["CGUS", "Capital Group Core Equity ETF", "0.44"],
  ["OPTZ", "Optimize Strategy Index ETF", "0.43"],
  ["PDP", "Invesco Dorsey Wright Momentum ETF", "0.40"],
  ["EAOM", "iShares ESG Aware 40/60 Moderate Allocation ETF", "0.39"],
  ["XT", "iShares Exponential Technologies ETF", "0.36"],
  ["AOM", "iShares Core 40/60 Moderate Allocation ETF", "0.36"],
  ["IRTR", "Ishares Lifepath Retirement ETF", "0.35"],
  ["LSVD", "LSV Disciplined Value ETF", "0.34"],
  ["PRF", "Invesco RAFI US 1000 ETF", "0.31"],
  ["SYII", "Syntax Stratified Total Market II ETF", "0.30"],
  ["SYUS", "Syntax Stratified U.S. Total Market ETF", "0.30"],
  ["SCIU", "Global X Scientific Beta US ETF", "0.30"],
  ["DFAC", "Dimensional U.S. Core Equity 2 ETF", "0.29"],
  ["NSCR", "Nuveen Sustainable Core ETF", "0.29"],
  ["FNDX", "Schwab Fundamental U.S. Large Company ETF", "0.29"],
  ["EAOK", "iShares ESG Aware 30/70 Conservative Allocation ETF", "0.29"],
  ["FNDB", "Schwab Fundamental U.S. Broad Market ETF", "0.27"],
  ["WRND", "NYLI Global Equity R&D Leaders ETF", "0.27"],
  ["AOK", "iShares Core 30/70 Conservative Allocation ETF", "0.27"],
  ["AFLG", "First Trust Active Factor Large Cap ETF", "0.26"],
  ["FAD", "First Trust Multi Cap Growth AlphaDEX Fund", "0.26"],
  ["RSP", "Invesco S&P 500 Equal Weight ETF", "0.21"],
  ["TPLE", "Timothy Plan US Large/Mid Cap Core Enhanced ETF", "0.20"],
  ["TPLC", "Timothy Plan US Large/Mid Cap Core ETF", "0.20"],
  ["FEX", "First Trust Large Cap Core AlphaDEX Fund", "0.18"],
  ["RSPA", "Invesco S&P 500 Equal Weight Income Advantage ETF", "0.17"],
  ["SSPY", "Stratified LargeCap Index ETF", "0.17"],
  ["SHUS", "Stratified LargeCap Hedged ETF", "0.17"],
  ["QUS", "SPDR MSCI USA StrategicFactors ETF", "0.15"],
  ["RAFE", "PIMCO RAFI ESG U.S. ETF PIMCO RAFI ESG U.S. ETF", "0.15"],
  ["EUSA", "iShares MSCI USA Equal Weighted ETF", "0.14"],
  ["GK", "AdvisorShares Gerber Kawasaki ETF", "0.13"],
  ["KOMP", "SPDR S&P Kensho New Economies Composite ETF", "0.13"],
  ["SIZE", "iShares MSCI USA Size Factor ETF", "0.13"],
  ["HKND", "Humankind US Stock ETF", "0.13"],
  ["QWLD", "SPDR MSCI World StrategicFactors ETF", "0.10"],
  ["CFO", "VictoryShares US 500 Enhanced Volatility Wtd ETF", "0.08"],
  ["CFA", "VictoryShares US 500 Volatility Wtd ETF", "0.08"],
  ["EQAL", "Invesco Russell 1000 Equal Weight ETF", "0.06"],
  ["AGOX", "Adaptive Alpha Opportunities ETF", "0.06"],
  ["EBI", "Longview Advantage ETF", "0.06"],
  ["ONEO", "SPDR Russell 1000 Momentum Focus ETF", "0.01"]
];